name: Build and Deploy
on:
  push:
    branches:    
      # Push events on main branch
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install
        run: |
          yarn
      - name: Deploy
        run: |
          yarn deploy
